spring:
  cloud:
    sentinel:
      enabled: true
      #心跳启动
      eager: true
      # sentinel控制台地址
      transport:
        dashboard: localhost:5001
      # nacos配置持久化
      datasource:
        flow:
          nacos:
            server-add: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-add: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
